spring.application.name=RCMU_Project

# Configuración de PostgreSQL usando Testcontainers (jdbc:tc)
# Esto levantará automáticamente un contenedor Docker de Postgres 16
spring.datasource.url=jdbc:tc:postgresql:16-alpine:///rcmu_db_test
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true