# Configuración de H2
spring.datasource.url=jdbc:h2:mem:rcmudb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para ver las tablas (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esta línea ayuda si tienes problemas de frames en el navegador
spring.queries.hibernate.default_schema=PUBLIC

# Hibernate - Esto crea las tablas automáticamente basado en los @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true